tetsing pbs

diff --git a/evaluation_1/Makefile b/evaluation_1/Makefile
--- a/evaluation_1/Makefile
+++ b/evaluation_1/Makefile
@@ -3,17 +3,18 @@
 #==============================
 
 # Runtime logging configuration
-RUNTIME_LOG_FLAGS := \
-	--log=fifo_scheduler.thres:debug \
-	--log=heft_scheduler.thres:debug \
-	--log=eft_scheduler.thres:debug \
-	--log=hardware.thres:debug
+# RUNTIME_LOG_FLAGS := \
+# 	--log=fifo_scheduler.thres:debug \
+# 	--log=heft_scheduler.thres:debug \
+# 	--log=eft_scheduler.thres:debug \
+# 	--log=hardware.thres:debug
 EXECUTABLE := ../bin/nflows $(RUNTIME_LOG_FLAGS)
 
 # Directories and Executables
 SCRIPTS_DIR := ../scripts
 PYTHON_EXEC := $(SCRIPTS_DIR)/.env/bin/python3
 SLURM_EXEC := /bin/sbatch --cpus-per-task=$(shell nproc)
+PBS_EXEC := /bin/qsub
 
 # Validation Scripts
 VALIDATE_OFFSETS := $(PYTHON_EXEC) $(SCRIPTS_DIR)/validate_offsets.py
@@ -21,7 +22,8 @@ VALIDATE_OUTPUT := $(PYTHON_EXEC) $(SCRIPTS_DIR)/validate_output.py
 
 # Configuration Generation Scripts
 GENERATE_CONFIG := $(PYTHON_EXEC) $(SCRIPTS_DIR)/generate_config.py
-GENERATE_SUBMIT := $(PYTHON_EXEC) $(SCRIPTS_DIR)/generate_submit.py
+GENERATE_SLURM := $(PYTHON_EXEC) $(SCRIPTS_DIR)/generate_slurm.py
+GENERATE_PBS := $(PYTHON_EXEC) $(SCRIPTS_DIR)/generate_pbs.py
 
 # Visualization and Reporting Scripts
 GENERATE_GANTT := $(PYTHON_EXEC) $(SCRIPTS_DIR)/generate_gantt.py
@@ -40,6 +42,7 @@ EVALUATION_LOG_DIR := $(EVALUATION_RESULT_DIR)/log
 EVALUATION_OUTPUT_DIR := $(EVALUATION_RESULT_DIR)/output
 EVALUATION_CONFIG_DIR := $(EVALUATION_RESULT_DIR)/config
 EVALUATION_SLURM_DIR := $(EVALUATION_RESULT_DIR)/slurm
+EVALUATION_PBS_DIR := $(EVALUATION_RESULT_DIR)/pbs
 
 EVALUATION_SLEEPTIME := 10
 EVALUATION_REPEATS := 5
@@ -138,22 +141,25 @@ $(EVALUATION_CONFIG_DIR)/%/.generated: $(EVALUATION_WORKFLOW_DIR)/%.dot
 .PHONY: all-yamls
 all-yamls: $(addsuffix .yaml, $(basename $(EVALUATION_WORKFLOWS)))
 
+# Slurm Job Generation and Submission
+
 .PRECIOUS: $(EVALUATION_SLURM_DIR)/%.slurm
 $(EVALUATION_SLURM_DIR)/%.slurm: $(EVALUATION_CONFIG_DIR)/%/.generated
 	@echo "[INFO] Generating SLURM job for: $*"
 	@mkdir -p "$(EVALUATION_SLURM_DIR)"
 	@CONFIG_DIR=$(EVALUATION_CONFIG_DIR)/$*; \
+	WORKFLOW_LOG_FILE=$(EVALUATION_LOG_DIR)/$*/workflow.log; \
 	find $$CONFIG_DIR -name config.json | while read -r CONFIG_FILE; do \
 		SLURM_FILE=$$(echo "$$CONFIG_FILE" | sed 's|/config/|/slurm/|' | sed 's|config.json|submit.sbatch|'); \
 		LOG_DIR=$$(echo "$$CONFIG_FILE" | sed 's|/config/|/log/|' | sed 's|config.json||'); \
 		mkdir -p "$$LOG_DIR"; \
-		$(GENERATE_SUBMIT) --job "$*" \
+		$(GENERATE_SLURM) --job "$*" \
 			--config_file "$$CONFIG_FILE" \
-			--execute_command "./$(EXECUTABLE) $(RUNTIME_LOG_FLAGS) $${CONFIG_FILE}" \
+			--execute_command "$(EXECUTABLE) $${CONFIG_FILE}" \
 			--validate_command "$(VALIDATE_OFFSETS)" \
 			--repeats $(EVALUATION_REPEATS) \
 			--log_dir "$$LOG_DIR" \
-			--output "$$SLURM_FILE" > /dev/null 2>&1; \
+			--output "$$SLURM_FILE" >> "$$WORKFLOW_LOG_FILE" 2>&1; \
 		GENERATE_STATUS=$$?; \
 		if [ $$GENERATE_STATUS -eq 0 ]; then \
 			printf "  [SUCCESS] $$SLURM_FILE\n"; \
@@ -171,8 +177,9 @@ $(EVALUATION_SLURM_DIR)/%.slurm: $(EVALUATION_CONFIG_DIR)/%/.generated
 $(EVALUATION_SLURM_DIR)/%.submitted: $(EVALUATION_SLURM_DIR)/%.slurm
 	@echo "[INFO] Submitting workflow: $*"
 	@SLURM_DIR=$(EVALUATION_SLURM_DIR)/$*; \
+	WORKFLOW_LOG_FILE=$(EVALUATION_LOG_DIR)/$*/workflow.log; \
 	find $$SLURM_DIR -name submit.sbatch | while read -r SLURM_FILE; do \
-		$(SLURM_EXEC) "$$SLURM_FILE" > /dev/null 2>&1; \
+		$(SLURM_EXEC) "$$SLURM_FILE" >> "$$WORKFLOW_LOG_FILE" 2>&1; \
 		SLURM_STATUS=$$?; \
 		if [ $$SLURM_STATUS -eq 0 ]; then \
 			printf "  [SUCCESS] $$SLURM_FILE\n"; \
@@ -183,5 +190,57 @@ $(EVALUATION_SLURM_DIR)/%.submitted: $(EVALUATION_SLURM_DIR)/%.slurm
 	@touch $@ # Create the sentinel file to indicate completion
 
 # Redirect target (so `make NAME.slurm` works)
-%.submit: $(EVALUATION_SLURM_DIR)/%.submitted
+%.submit_slurm: $(EVALUATION_SLURM_DIR)/%.submitted
+	@true
+
+# PBS Job Generation and Submission
+
+.PRECIOUS: $(EVALUATION_PBS_DIR)/%.pbs
+$(EVALUATION_PBS_DIR)/%.pbs: $(EVALUATION_CONFIG_DIR)/%/.generated
+	@echo "[INFO] Generating PBS job for: $*"
+	@mkdir -p "$(EVALUATION_PBS_DIR)"
+	@CONFIG_DIR=$(EVALUATION_CONFIG_DIR)/$*; \
+	WORKFLOW_LOG_FILE=$(EVALUATION_LOG_DIR)/$*/workflow.log; \
+	find $$CONFIG_DIR -name config.json | while read -r CONFIG_FILE; do \
+		PBS_FILE=$$(echo "$$CONFIG_FILE" | sed 's|/config/|/pbs/|' | sed 's|config.json|submit.sbatch|'); \
+		LOG_DIR=$$(echo "$$CONFIG_FILE" | sed 's|/config/|/log/|' | sed 's|config.json||'); \
+		mkdir -p "$$LOG_DIR"; \
+		$(GENERATE_PBS) --job "$*" \
+			--config_file "$$CONFIG_FILE" \
+			--execute_command "$(EXECUTABLE) $${CONFIG_FILE}" \
+			--validate_command "$(VALIDATE_OFFSETS)" \
+			--repeats $(EVALUATION_REPEATS) \
+			--log_dir "$$LOG_DIR" \
+			--output "$$PBS_FILE" >> "$$WORKFLOW_LOG_FILE" 2>&1; \
+		GENERATE_STATUS=$$?; \
+		if [ $$GENERATE_STATUS -eq 0 ]; then \
+			printf "  [SUCCESS] $$PBS_FILE\n"; \
+		else \
+			printf "  [FAILED] $$PBS_FILE (Generate: $$GENERATE_STATUS)\n"; \
+		fi; \
+	done
+	@touch $@ # Create the sentinel file to indicate completion
+
+# Redirect target (so `make NAME.pbs` works)
+%.pbs: $(EVALUATION_PBS_DIR)/%.pbs
+	@true
+
+.PRECIOUS: $(EVALUATION_PBS_DIR)/%.submitted
+$(EVALUATION_PBS_DIR)/%.submitted: $(EVALUATION_PBS_DIR)/%.pbs
+	@echo "[INFO] Submitting workflow: $*"
+	@PBS_DIR=$(EVALUATION_PBS_DIR)/$*; \
+	WORKFLOW_LOG_FILE=$(EVALUATION_LOG_DIR)/$*/workflow.log; \
+	find $$PBS_DIR -name submit.sbatch | while read -r PBS_FILE; do \
+		$(PBS_EXEC) "$$PBS_FILE" >> "$$WORKFLOW_LOG_FILE" 2>&1; \
+		PBS_STATUS=$$?; \
+		if [ $$PBS_STATUS -eq 0 ]; then \
+			printf "  [SUCCESS] $$PBS_FILE\n"; \
+		else \
+			printf "  [FAILED] $$PBS_FILE (Generate: $$PBS_STATUS)\n"; \
+		fi; \
+	done
+	@touch $@ # Create the sentinel file to indicate completion
+
+# Redirect target (so `make NAME.slurm` works)
+%.submit_pbs: $(EVALUATION_PBS_DIR)/%.submitted
 	@true
