Submit workflows automatically, Add new config templates, Fixed incorrect bit mask parsin (#32)
* add system topology file and fix slurm submission

* Fix core avail mask, implement core_avail_ids

* Fix slurm generation

* update makefiles to automate all workflows submission

diff --git a/evaluation_1/Makefile b/evaluation_1/Makefile
--- a/evaluation_1/Makefile
+++ b/evaluation_1/Makefile
@@ -13,6 +13,7 @@ EXECUTABLE := ../bin/nflows $(RUNTIME_LOG_FLAGS)
 # Directories and Executables
 SCRIPTS_DIR := ../scripts
 PYTHON_EXEC := $(SCRIPTS_DIR)/.env/bin/python3
+SLURM_EXEC := /bin/sbatch --cpus-per-task=$(shell nproc)
 
 # Validation Scripts
 VALIDATE_OFFSETS := $(PYTHON_EXEC) $(SCRIPTS_DIR)/validate_offsets.py
@@ -75,6 +76,7 @@ clean: backup
 	done
 
 # Rule: sentinel file depends on input DOT file
+.PRECIOUS: $(EVALUATION_CONFIG_DIR)/%/.generated
 $(EVALUATION_CONFIG_DIR)/%/.generated: $(EVALUATION_WORKFLOW_DIR)/%.dot
 	@echo "[INFO] Generating configs for workflow: $*"
 	@for group in $(EVALUATION_GROUPS); do \
@@ -86,11 +88,12 @@ $(EVALUATION_CONFIG_DIR)/%/.generated: $(EVALUATION_WORKFLOW_DIR)/%.dot
 			mkdir -p $$CONFIG_DIR $$OUTPUT_DIR $$LOG_DIR; \
 			CONFIG_FILE=$$CONFIG_DIR/config.json; \
 			OUTPUT_FILE=$$OUTPUT_DIR/output.yaml; \
-			LOG_FILE=$$LOG_DIR/log.txt; \
+			LOG_FILE=$$LOG_DIR/workflow.log; \
 			$(GENERATE_CONFIG) \
 				--template "$$json_template" \
-				--output_file "$$CONFIG_FILE" >> "$$LOG_FILE" 2>&1 \
-				--params out_file_name="$$OUTPUT_FILE" dag_file="$(EVALUATION_WORKFLOW_DIR)/$*.dot"; \
+				--output_file "$$CONFIG_FILE" \
+				--params out_file_name="$$OUTPUT_FILE" dag_file="$(EVALUATION_WORKFLOW_DIR)/$*.dot" \
+				>> "$$LOG_FILE" 2>&1; \
 			GENERATE_STATUS=$$?; \
 			if [ $$GENERATE_STATUS -eq 0 ]; then \
 				printf "  [SUCCESS] $$CONFIG_FILE\n"; \
@@ -105,8 +108,6 @@ $(EVALUATION_CONFIG_DIR)/%/.generated: $(EVALUATION_WORKFLOW_DIR)/%.dot
 %.json: $(EVALUATION_CONFIG_DIR)/%/.generated
 	@true # This rule is a placeholder to ensure the directory exists
 
-.PRECIOUS: $(EVALUATION_CONFIG_DIR)/%/.generated
-
 %.yaml: %.json
 	@echo "[INFO] Running workflow executions for: $*"
 	@CONFIG_DIR=$(EVALUATION_CONFIG_DIR)/$*; \
@@ -117,7 +118,7 @@ $(EVALUATION_CONFIG_DIR)/%/.generated: $(EVALUATION_WORKFLOW_DIR)/%.dot
 			DST_FILE=$$(echo "$$CONFIG_FILE" | sed 's|/config/|/output/|' | sed 's|config.json|'"$$repeat"'.yaml|'); \
 			mkdir -p "$$(dirname $$LOG_FILE)"; \
 			START_TIME=$$(date +%s.%N); \
-			./$(EXECUTABLE) "$${CONFIG_FILE}" >  "$$LOG_FILE" 2>&1; \
+			$(EXECUTABLE) "$${CONFIG_FILE}" >  "$$LOG_FILE" 2>&1; \
 			EXECUTABLE_STATUS=$$?; \
 			END_TIME=$$(date +%s.%N); \
 			ELAPSED_TIME_SEC=$$(echo "$$END_TIME - $$START_TIME" | bc); \
@@ -134,19 +135,24 @@ $(EVALUATION_CONFIG_DIR)/%/.generated: $(EVALUATION_WORKFLOW_DIR)/%.dot
 		done; \
 	done
 
-.PRECIOUS: $(EVALUATION_SLURM_DIR)/%.slurm
+.PHONY: all-yamls
+all-yamls: $(addsuffix .yaml, $(basename $(EVALUATION_WORKFLOWS)))
 
+.PRECIOUS: $(EVALUATION_SLURM_DIR)/%.slurm
 $(EVALUATION_SLURM_DIR)/%.slurm: $(EVALUATION_CONFIG_DIR)/%/.generated
 	@echo "[INFO] Generating SLURM job for: $*"
 	@mkdir -p "$(EVALUATION_SLURM_DIR)"
 	@CONFIG_DIR=$(EVALUATION_CONFIG_DIR)/$*; \
 	find $$CONFIG_DIR -name config.json | while read -r CONFIG_FILE; do \
 		SLURM_FILE=$$(echo "$$CONFIG_FILE" | sed 's|/config/|/slurm/|' | sed 's|config.json|submit.sbatch|'); \
+		LOG_DIR=$$(echo "$$CONFIG_FILE" | sed 's|/config/|/log/|' | sed 's|config.json||'); \
+		mkdir -p "$$LOG_DIR"; \
 		$(GENERATE_SUBMIT) --job "$*" \
-			--config_file "$$CONFIG_DIR" \
+			--config_file "$$CONFIG_FILE" \
 			--execute_command "./$(EXECUTABLE) $(RUNTIME_LOG_FLAGS) $${CONFIG_FILE}" \
 			--validate_command "$(VALIDATE_OFFSETS)" \
 			--repeats $(EVALUATION_REPEATS) \
+			--log_dir "$$LOG_DIR" \
 			--output "$$SLURM_FILE" > /dev/null 2>&1; \
 		GENERATE_STATUS=$$?; \
 		if [ $$GENERATE_STATUS -eq 0 ]; then \
@@ -156,7 +162,26 @@ $(EVALUATION_SLURM_DIR)/%.slurm: $(EVALUATION_CONFIG_DIR)/%/.generated
 		fi; \
 	done
 	@touch $@ # Create the sentinel file to indicate completion
-	
+
 # Redirect target (so `make NAME.slurm` works)
 %.slurm: $(EVALUATION_SLURM_DIR)/%.slurm
+	@true
+
+.PRECIOUS: $(EVALUATION_SLURM_DIR)/%.submitted
+$(EVALUATION_SLURM_DIR)/%.submitted: $(EVALUATION_SLURM_DIR)/%.slurm
+	@echo "[INFO] Submitting workflow: $*"
+	@SLURM_DIR=$(EVALUATION_SLURM_DIR)/$*; \
+	find $$SLURM_DIR -name submit.sbatch | while read -r SLURM_FILE; do \
+		$(SLURM_EXEC) "$$SLURM_FILE" > /dev/null 2>&1; \
+		SLURM_STATUS=$$?; \
+		if [ $$SLURM_STATUS -eq 0 ]; then \
+			printf "  [SUCCESS] $$SLURM_FILE\n"; \
+		else \
+			printf "  [FAILED] $$SLURM_FILE (Generate: $$SLURM_STATUS)\n"; \
+		fi; \
+	done
+	@touch $@ # Create the sentinel file to indicate completion
+
+# Redirect target (so `make NAME.slurm` works)
+%.submit: $(EVALUATION_SLURM_DIR)/%.submitted
 	@true
